version: 2
root-markers:
  - .git/
  - .svn/
lint-debounce: 1s

tools:
  vint-lint: &vint-lint
    prefix: 'vint'
    lint-command: 'vint --enable-neovim --style-problem --stdin-display-name ${INPUT} -'
    lint-stdin: true

  jq-format: &jq-format
    format-command: 'jq .'
    format-stdin: true

  shellcheck-lint: &shellcheck-lint
    prefix: 'shellcheck'
    lint-command: 'shellcheck -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t%*[^:]: %m [SC%n]'

  shfmt-format: &shfmt-format
    format-command: 'shfmt -ln bash -i 2 -bn -ci -sr -kp'
    format-stdin: true

  flake8-lint: &flake8-lint
    prefix: 'flake8'
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
      - setup.cfg
      - tox.ini
      - .flake8

  black-format: &black-format
    commands:
      - command: 'black --quiet --safe ${INPUT}'
        title: 'black format'

  yamllint-lint: &yamllint-lint
    prefix: 'yamllint'
    lint-command: 'yamllint --strict --format parsable ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: [%t%*[a-z]] %m'
    env:
      - 'PYTHONIOENCODING=UTF-8'

  rstcheck-lint: &rstcheck-lint
    prefix: 'rstcheck'
    lint-command: 'rstcheck --report warning -'
    lint-stdin: true
    lint-formats:
      - '%f:%l: (%t%*[^/]/%n) %m'

  eslint-lint: &eslint-lint
    prefix: 'eslint'
    lint-command: 'npx --no-install eslint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json
    commands:
      - command: 'npx --no-install eslint --fix ${INPUT}'
        title: 'eslint fix'

  stylelint-lint: &stylelint-lint
    prefix: 'stylelint'
    lint-command: 'npx --no-install stylelint --formatter unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: false
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%t%*[a-z]]'
    root-markers:
      - .stylelintrc.json
    commands:
      - command: 'npx --no-install stylelint --fix ${INPUT}'
        title: 'stylelint fix'

  htmllint-lint: &htmllint-lint
    prefix: 'htmllint'
    lint-command: 'npx --no-install htmllint ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f: line %l, col %c, %m'
    root-markers:
      - .htmllintrc

languages:
  vim:
    - <<: *vint-lint

  markdown:
    - <<: *stylelint-lint

  json:
    - <<: *jq-format

  sh:
    - <<: *shellcheck-lint
    - <<: *shfmt-format

  yaml:
    - <<: *yamllint-lint

  rst:
    - <<: *rstcheck-lint

  javascript:
    - <<: *eslint-lint

  typescript:
    - <<: *eslint-lint

  css:
    - <<: *stylelint-lint

  scss:
    - <<: *stylelint-lint

  sass:
    - <<: *stylelint-lint

  less:
    - <<: *stylelint-lint

  sugarss:
    - <<: *stylelint-lint

  python:
    - <<: *flake8-lint
    - <<: *black-format

  html:
    - <<: *htmllint-lint
    - <<: *stylelint-lint
