display-name = "Daniel M. Capella"
downloads-dir = "~/download"
signature = """
Best,
Daniel <https://danielcapella.com>
"""

[arch-local]
default = true
email = "polyzen@archlinux.org"
pgp-encrypt-cmd = "gpg -o - -eqar"
pgp-decrypt-cmd = "gpg -dq"

sender = "smtp"
smtp-host = "mail.archlinux.org"
smtp-port = 465
smtp-login = "polyzen"
smtp-passwd-cmd = "pass services/email/polyzen@archlinux.org"

backend = "maildir"
maildir-root-dir = "~/.mail/arch"

[arch-local.folder-aliases]
inbox = "~/.mail/arch/INBOX"
