display-name = "Daniel M. Capella"
downloads-dir = "~/download"
signature = """
Best,
Daniel <https://danielcapella.com>
"""

[arch-local]
default = true
email = "polyzen@archlinux.org"
pgp-encrypt-cmd = "gpg -o - -eqar"
pgp-decrypt-cmd = "gpg -dq"

sender = "smtp"
smtp-host = "mail.archlinux.org"
smtp-port = 465
smtp-login = "polyzen"
smtp-auth = "passwd"
smtp-passwd = { cmd = "rbw get --folder services/email polyzen" }

backend = "notmuch"
notmuch-db-path = "~/.mail"

[arch-local.folder-aliases]
inbox = "tag:inbox"
